//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNRPS.POIMS.CommonResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DNRPS.POIMS.CommonResources.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concurrency issue detected!&lt;br /&gt;The loaded &quot;{0}&quot; [ &lt;u&gt;{1}&lt;/u&gt; ] that you are attempting to change now&lt;br /&gt;has already been updated by &lt;u&gt;{2}&lt;/u&gt; at an earlier time [ {3} ]..
        /// </summary>
        public static string HtmlConcurrencyIssuesDetectedForItem_Arg0ItemNameArg1RecordNoArg2UpdatedByArg3UpdatedAt {
            get {
                return ResourceManager.GetString("HtmlConcurrencyIssuesDetectedForItem_Arg0ItemNameArg1RecordNoArg2UpdatedByArg3Upd" +
                        "atedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Loading Software License!&lt;br /&gt;{0}.
        /// </summary>
        public static string HtmlErrorLoadingSoftwareLicense_Arg0ErrorDetail {
            get {
                return ResourceManager.GetString("HtmlErrorLoadingSoftwareLicense_Arg0ErrorDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! The system has encountered some error.&lt;br /&gt;Please try again later.&lt;br /&gt;&lt;br /&gt;&lt;i&gt;Note: If the error persists, please contact your administrator for further assistance.&lt;/i&gt;.
        /// </summary>
        public static string HtmlGenericErrorMessage {
            get {
                return ResourceManager.GetString("HtmlGenericErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have the necessary privilege(s) to perform the requested operation.&lt;br /&gt;{0}&lt;br /&gt;&lt;i&gt;Please contact your administrator for assistance.&lt;/i&gt;.
        /// </summary>
        public static string HtmlInvalidPrivilegeError_Arg0PrivilegesInfo {
            get {
                return ResourceManager.GetString("HtmlInvalidPrivilegeError_Arg0PrivilegesInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;{0}&quot; is already in use.&lt;br /&gt;Please use a unique &quot;{0}&quot;..
        /// </summary>
        public static string HtmlItemAlreadyInUse_Arg0ItemName {
            get {
                return ResourceManager.GetString("HtmlItemAlreadyInUse_Arg0ItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! The page you have requested for does not exists.&lt;br /&gt;&lt;br /&gt;&lt;i&gt;Note: If you reach this page when using the system normally, please contact your administrator for further assistance.&lt;/i&gt;.
        /// </summary>
        public static string HtmlPageNotFoundErrorMessage {
            get {
                return ResourceManager.GetString("HtmlPageNotFoundErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You require &lt;u&gt;ALL&lt;/u&gt; of the following privilege(s):&lt;br /&gt;{0}.
        /// </summary>
        public static string HtmlRequireAllOfTheFollowingPrivileges_Arg0PrivilegeList {
            get {
                return ResourceManager.GetString("HtmlRequireAllOfTheFollowingPrivileges_Arg0PrivilegeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You require &lt;u&gt;AT LEAST ONE&lt;/u&gt; of the following privilege(s):&lt;br /&gt;{0}.
        /// </summary>
        public static string HtmlRequireOneOfTheFollowingPrivileges_Arg0PrivilegeList {
            get {
                return ResourceManager.GetString("HtmlRequireOneOfTheFollowingPrivileges_Arg0PrivilegeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid {0}..
        /// </summary>
        public static string InvalidItem_Arg0ItemName {
            get {
                return ResourceManager.GetString("InvalidItem_Arg0ItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid &quot;{0}&quot; is required..
        /// </summary>
        public static string ItemIsRequired_Arg0ItemName {
            get {
                return ResourceManager.GetString("ItemIsRequired_Arg0ItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Error.
        /// </summary>
        public static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or Password is incorrect..
        /// </summary>
        public static string LoginErrorMessage {
            get {
                return ResourceManager.GetString("LoginErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing configuration settings for &quot;{0}&quot; in config file!.
        /// </summary>
        public static string MissingConfigSetting_Arg0SettingName {
            get {
                return ResourceManager.GetString("MissingConfigSetting_Arg0SettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object {0} must not be null!.
        /// </summary>
        public static string ObjectMustNotBeNull_Arg0Name {
            get {
                return ResourceManager.GetString("ObjectMustNotBeNull_Arg0Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create the &quot;{0}&quot;!.
        /// </summary>
        public static string UnableToCreateItem_Arg0Name {
            get {
                return ResourceManager.GetString("UnableToCreateItem_Arg0Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete the &quot;{0}&quot;!.
        /// </summary>
        public static string UnableToDeleteItem_Arg0Name {
            get {
                return ResourceManager.GetString("UnableToDeleteItem_Arg0Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Generating Serial Number for {0}!.
        /// </summary>
        public static string UnableToGenerateSerialNumberForItem_Arg0ItemName {
            get {
                return ResourceManager.GetString("UnableToGenerateSerialNumberForItem_Arg0ItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open new browser window. Please allow pop-up for this site..
        /// </summary>
        public static string UnableToOpenNewPopUpWindow {
            get {
                return ResourceManager.GetString("UnableToOpenNewPopUpWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read from {0}!.
        /// </summary>
        public static string UnableToPerformInputRead_Arg0Name {
            get {
                return ResourceManager.GetString("UnableToPerformInputRead_Arg0Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to write to {1}!.
        /// </summary>
        public static string UnableToPerformOutputWrite_Arg0Name {
            get {
                return ResourceManager.GetString("UnableToPerformOutputWrite_Arg0Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update the &quot;{0}&quot;!.
        /// </summary>
        public static string UnableToUpdateItem_Arg0Name {
            get {
                return ResourceManager.GetString("UnableToUpdateItem_Arg0Name", resourceCulture);
            }
        }
    }
}
