//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNRPS.POIMS.CommonResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DNRPS.POIMS.CommonResources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to delete record.
        /// </summary>
        public static string ClickToDeleteRecord {
            get {
                return ResourceManager.GetString("ClickToDeleteRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to edit record.
        /// </summary>
        public static string ClickToEditRecord {
            get {
                return ResourceManager.GetString("ClickToEditRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation Dialog.
        /// </summary>
        public static string ConfirmationDialog {
            get {
                return ResourceManager.GetString("ConfirmationDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created {0} ( {1} )..
        /// </summary>
        public static string CreatedItem_Arg0ItemArg1Name {
            get {
                return ResourceManager.GetString("CreatedItem_Arg0ItemArg1Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POIMS will automatically perform routine database maintenance to ensure system robustness and optimal database performance..
        /// </summary>
        public static string DatabaseMaintenanceNote1 {
            get {
                return ResourceManager.GetString("DatabaseMaintenanceNote1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For optimal performance, it is recommended for you to retain the default settings..
        /// </summary>
        public static string DatabaseMaintenanceNote2 {
            get {
                return ResourceManager.GetString("DatabaseMaintenanceNote2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted {0} ( {1} )..
        /// </summary>
        public static string DeletedItem_Arg0ItemArg1Name {
            get {
                return ResourceManager.GetString("DeletedItem_Arg0ItemArg1Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} &quot;{1}&quot; has been created successfully!.
        /// </summary>
        public static string HtmlCreateItemSuccess_Arg0ItemArg1Name {
            get {
                return ResourceManager.GetString("HtmlCreateItemSuccess_Arg0ItemArg1Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you wish to delete the {0} &quot;{1}&quot;?.
        /// </summary>
        public static string HtmlDeleteItem_Arg0ItemArg1Name {
            get {
                return ResourceManager.GetString("HtmlDeleteItem_Arg0ItemArg1Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;i&gt;Saved by &lt;b&gt;{0}&lt;/b&gt; @ {1}&lt;/i&gt;.
        /// </summary>
        public static string HtmlSavedBySomeoneAtSometime_Arg0NameArg1Time {
            get {
                return ResourceManager.GetString("HtmlSavedBySomeoneAtSometime_Arg0NameArg1Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} &quot;{1}&quot; has been updated successfully!.
        /// </summary>
        public static string HtmlUpdateItemSuccess_Arg0ItemArg1Name {
            get {
                return ResourceManager.GetString("HtmlUpdateItemSuccess_Arg0ItemArg1Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;{0}&lt;/b&gt;.
        /// </summary>
        public static string HtmlWelcomeUserName_Arg0Name {
            get {
                return ResourceManager.GetString("HtmlWelcomeUserName_Arg0Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}).
        /// </summary>
        public static string ParameterAndUomLabelFormat_Arg0ParamArg1Uom {
            get {
                return ResourceManager.GetString("ParameterAndUomLabelFormat_Arg0ParamArg1Uom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success Dialog.
        /// </summary>
        public static string SuccessDialog {
            get {
                return ResourceManager.GetString("SuccessDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated {0} ( {1} )..
        /// </summary>
        public static string UpdatedItem_Arg0ItemArg1Name {
            get {
                return ResourceManager.GetString("UpdatedItem_Arg0ItemArg1Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed {0} : From [ {1} ] To [ {2} ].
        /// </summary>
        public static string UpdatedParamFromOldValueToNewValue_Arg0ParamNameArg1OldValueArg2NewValue {
            get {
                return ResourceManager.GetString("UpdatedParamFromOldValueToNewValue_Arg0ParamNameArg1OldValueArg2NewValue", resourceCulture);
            }
        }
    }
}
